### ISSUE TITLE
Doing co-evolution on case studies

### ISSUE THREAD

**Issue by timsanwald** [CoWolf/CoWolf#124]
|  |  |
| --- | --- |
| **As an** | End user |
| **I want to** | know, that the software is useable |
| **to** | decide which tool I should use |

**Done When**
- [x] refs #270  Enhance statechart model 
- [x]  The case studies are working with CoWolf
- [x] refs #243 Convert [StateChart](https://github.com/DevProjectSS2014/Resources/tree/master/Ensure/Models/de.stuttgart.informatik.PPU.SCmodels) Model instances (add ID's)    
- [x] refs  #244 Convert [Component](https://github.com/DevProjectSS2014/Resources/tree/master/Ensure/Models/de.stuttgart.informatik.PPU.SAmodels) Model instances (add ID's)  
- [x] refs #245 Convert [Fault tree 1](https://github.com/DevProjectSS2014/Resources/tree/master/Ensure/Models/de.stuttgart.informatik.PPU.FT1models)  Model instances (add ID's)  
- [ ] refs #246 Convert [Fault tree 2](https://github.com/DevProjectSS2014/Resources/tree/master/Ensure/Models/de.stuttgart.informatik.PPU.FT2models)  Model instances (add ID's)
