### ISSUE TITLE
Evolution of models

### ISSUE THREAD

**Issue by timsanwald** [CoWolf/CoWolf#128]
|  |  |
| --- | --- |
| **As an** | End user |
| **I want to** | evolve all my models (DTMC, CTMC, Component diagram, Activity chart, Faulttree, LQN) |
| **to** | see the evolution of my project |

**Done When**
- The atomic evolution rules for each model are specified
- The evolution for each model can be triggered with the evolution menu item

**Subtasks**
- [x] #142 Evolution rules for CTMC
- [x] #143 Evolution rules for LQN
- [x] #144 Evolution rules for Component diagram
- [x] #146 Evolution rules for Faulttree
- [x] #148 Evolution rules for DTMC
- [x] #174 Implement EvolutionManager for the models
- [ ] #227 Evolution rules for Sequence diagrams

**Comment by philippniethammer** [comment]
Assigned to @MinoQuarius @philippniethammer @zimmerml
