### ISSUE TITLE
Co-evolve manually

### ISSUE THREAD

**Issue by timsanwald** [CoWolf/CoWolf#13]
|  |  |
| --- | --- |
| **As an** | End user |
| **I want to** | manually co-evolve models (statechart & dtmc) |
| **to** | be able to decide independently what I want to coevolve |

**Done When:**
- [x] Create a menu item to start the transformation
- [x] Create transformation rules (ref #75 )
- [x] How traces should be handled (ref #79)
- [x] Mapping between diff and transformation rules (ref #78)
- [x] Perform transformation (ref #76)
- [x] Present the results (ref #80)
- [x] Specify the result file (ref #158)
- [x] Evolve-Dialogue: Checkbox "Add to Association Manager" (ref #113)

**Comment by philippniethammer** [comment]
Assigned (Sprint 4): @mlBob, @ReneTrefft
