### ISSUE TITLE
Coevolution of Component diagrams and faulttrees

### ISSUE THREAD

**Issue by timsanwald** [CoWolf/CoWolf#130]
|  |  |
| --- | --- |
| **As an** | End user |
| **I want to** | coevolve component diagrams with fault trees |
| **to** | hold them consistent |

**Done When:**
- Transformations are defined
- A coevolution from components to faults can be done, and vice versa
- After a coevolution from components to faults, the reverse operation does nothing

Tasks:
- [x] Create transformation rules from component diagram to fault tree. #197
- [x] Create transformation rules from fault tree to component diagram. #198
- [x] Create Mappings from difference to transformation rules. #199

**Comment by equiFX** [comment]
#197 #198 and #199 are out-dated, because we decided to integrated the ensure project for this transformation.
