### ISSUE TITLE
Coevolution of CTMC and DTMC

### ISSUE THREAD

**Issue by timsanwald** [CoWolf/CoWolf#131]
|  |  |
| --- | --- |
| **As an** | End user |
| **I want to** | coevolve CTMCs with DTMCs |
| **to** | hold them consistent |

**Done When:**
- Transformations are defined
- A coevolution from DTMC to CTMC can be done, and vice versa
- After a coevolution from DTMC to CTMC, the reverse operation does nothing
- [ ] Create coevolution rules from CTMC to DTMC. #147
- [ ] Create coevolution rules from DTMC to CTMC and ask for default values. #149
- [ ] Create rule mapping from evolution difference to transformation. #150
- [ ] Create neccessary projects for CTMC - DTMC transformation. (create skeleton structure ref #121) #151
- [ ] Test transformations (CTMC - DTMC) in both directions. #152

@jonasscheurich 
@verenya 
@equiFX
