### ISSUE TITLE
Co-evolve automatically

### ISSUE THREAD

**Issue by timsanwald** [CoWolf/CoWolf#14]
|  |  |
| --- | --- |
| **As an** | End user |
| **I want to** | automatically co-evolve models |
| **to** | hold models consistent |

**Done When:**
- [x] a) Create description of automatic Co-evolve (on save trigger)  (#210) 
- [x] b) Create description of hierarchical Co-evolution (manual trigger) (#211)
- [x] Clarify what Customer wants (a or b) (#212)
- [x] Research Versioning of files (#213)

[X] a:
- [ ] Find extension point for on save action (#214)
- [ ] Invalidate associated models that are not syncronized (#215)

[NOT] b:
- [INVALID] Calculate co-evolution strategy (#216)
- [INVALID] Run Co-Evolution according strategy (#217)

**Follows:**
- [ ] #13 Co-evolve manually
