### ISSUE TITLE
User defined meta transformation

### ISSUE THREAD

**Issue by timsanwald** [CoWolf/CoWolf#15]
|  |  |
| --- | --- |
| **As an** | Maintenance engineer |
| **I want to** | create transformation rules |
| **to** | co-evolve the user defined models with other models |

**Done When:**
- [ ] Define the transformation language
- [ ] Create interfaces, which are used to perform the transformation
- [ ] Implement interfaces

**Follows:**
- [ ] #13 Co-evolve manually

**Comment by jonasscheurich** [comment]
First: For every transformation one plugin

Second: Generic version with henshin import
