### ISSUE TITLE
Reliability analysis (CTMC)

### ISSUE THREAD

**Issue by timsanwald** [CoWolf/CoWolf#159]
|  |  |
| --- | --- |
| **As an** | End user |
| **I want to** | evaluate the reliability model (CTMC) |
| **to** | predict or analyse the reliability of my system |

**Done When:**
- [ ] #194 Ask Sinem what she wants to evaluate
- [ ] #195 Transfer the CTMC model to an external program to evaluate
- [ ] #196 Nice presentation of the results of CTMC reliability analysis
- [ ] #222 Create GUI to create / edit properties to evaluate
