### ISSUE TITLE
Differences between evolution steps

### ISSUE THREAD

**Issue by timsanwald** [CoWolf/CoWolf#16]
|  |  |
| --- | --- |
| **As an** | End user |
| **I want to** | see the evolution of statecharts |
| **to** | verify the automatic evolution |

**Done When:**
- [x] Add Menu item when referencing 2 instances of same model, which calculates the evolution steps (ref #39)
- [x] Get needed henshin rules for a statechart evolution (ref #40)
- [x] Execute SiDiff & SiLift (ref #41)
- [x] Create a nice presentation for the differences as logs (ref #42)

**Done by:**
- @equiFX 
- @zimmerml 
- @ReneTrefft
- @mlBob
