### ISSUE TITLE
Reliability certification

### ISSUE THREAD

**Issue by timsanwald** [CoWolf/CoWolf#17]
|  |  |
| --- | --- |
| **As an** | End user |
| **I want to** | evaluate the reliability model |
| **to** | predict or analyse the reliability of my system |

**Subtasks**
- [x] #44 Ask Sinem about dtmc model edit view
- [x] #45 Create ui to define properties
- [x] #46 Extend Preferences for CoWolf settings
- [x] #47 Show progress bar certification
- [x] #48 Show results in view
- [x] #49 Export the result as csv

**Done When:**
- [x] Transfer the model to the external program model type
- [x] Provide the properties to calculate the quality
- [x] Run the external program with the exported model and the properties
- [x] Nice presentation of the results

**Follows:**
- [ ] #21 Create reliability model (DTMC)
- [ ] #20 Create architectural model (Statechart)
