### ISSUE TITLE
Performance certification (LQN)

### ISSUE THREAD

**Issue by timsanwald** [CoWolf/CoWolf#18]
|  |  |
| --- | --- |
| **As an** | End user |
| **I want to** | evaluate the performance model |
| **to** | predict or analyse the performance of my system |

**Subtasks**
- [ ] #83 Create ui to define properties
- [ ] #103 Extend Preferences for CoWolf settings
- [ ] #104 Show progress bar certification
- [ ] #105 Show results in view
- [ ] #106 Transfer the model to the external program model type

**Done When:**
- [ ] Transfer the model to the external program model type
- [ ] Provide the properties to calculate the quality
- [ ] Run the external program with the exported model and the properties
- [ ] Nice presentation of the results

**Follows:**
- [ ] #96 Meta-Model LQN

**Comment by philippniethammer** [comment]
Assigned (Sprint 4): @maborjan
