### ISSUE TITLE
Safety certification

### ISSUE THREAD

**Issue by timsanwald** [CoWolf/CoWolf#19]
|  |  |
| --- | --- |
| **As an** | End user |
| **I want to** | evaluate the safety model |
| **to** | predict or analyse the safety of my system |

**Subtasks:**
- [x] Ask Sinem which calculations from the safety model have to be implemented #50
- [ ] Create UI to run the certification #51
- [x] Develop connectivity to xFTA #52
- [ ] Develop results' view for safety certification #53 
- [x] Implement xFTA generator #69 

**Follows:**
- [ ] #23 Create safety model (Fault Tree)
- [ ] #25 Create architecture model (Component Diagram)
