### ISSUE TITLE
Create architecture model (Statechart)

### ISSUE THREAD

**Issue by timsanwald** [CoWolf/CoWolf#20]
|  |  |
| --- | --- |
| **As an** | End user |
| **I want to** | create an [statechart](http://www.emn.fr/z-info/atlanmod/index.php/Ecore#Statecharts_1.0) of the system |
| **to** | define the architecture |

**Done When:**
- [x] Define a wizard to create the model file
- [x] Make the model editable with text editor
- [x] Add evolution rules

**Subtasks**
- [x] #59 Define a wizard to create the model file (with root node as default)
- [x] #60 Make the model editable with text editor (xtext)
- ~~[ ] #61 Add evolution rules for statechart~~
