### ISSUE TITLE
Create reliability model (DTMC)

### ISSUE THREAD

**Issue by timsanwald** [CoWolf/CoWolf#21]
|  |  |
| --- | --- |
| **As an** | End user |
| **I want to** | create a [DTMC](http://www.emn.fr/z-info/atlanmod/index.php/Ecore#DTMP_.28discrete_time_Markov_processes.29_1.0) |
| **to** | model the reliability of my system |

**Done When:**
- [x] Define a wizard to create the model file
- [x] Make the model editable with text editor
- [ ] Add evolution rules

**Subtasks**
- [x] #55 Define ecore model for dtmc and save it in the Ressources drectory
- [x] #56 Define a wizard to create the model file (with root node as default)
- [x] #57 Make the model editable with text editor (xtext)
- [ ] #58 Add evolution rules for dtmc
