### ISSUE TITLE
Coevolution of Sequence diagrams to LQN

### ISSUE THREAD

**Issue by timsanwald** [CoWolf/CoWolf#237]
|  |  |
| --- | --- |
| **As an** | End user |
| **I want to** | coevolve from sequence diagrams to lqn |
| **to** | evaluate the performance with the LQN model |

**Pre Conditions:**
- [x] #240 Sequence diagram graphical editor working

**Done When:**
- [x] #306 Change LQN Metamodel
- [x]  #267 Create SD2LQN Projects
- [ ] #268 Define Henshin SD2LQN Transformations 
- [ ] A coevolution from Sequences to LQNs can be done
