### ISSUE TITLE
Create an individual model

### ISSUE THREAD

**Issue by timsanwald** [CoWolf/CoWolf#24]
|  |  |
| --- | --- |
| **As an** | Maintenance engineer |
| **I want to** | add additional models as plugins |
| **to** | be able to co-evolve them with the other models |

**Done When:**
- [x] #107 Define a wizard interface to create the model file
- [x] #108 Define a wizard interface to analyse qos models
- [x] #109 Define a wizard inteface to evolve models (First page direction + individual pages)
- [x] #110 Create folders for each model extension
- [x] #111 Define evolution rules interfaces
- [x] preference entry
