### ISSUE TITLE
Research topics

### ISSUE THREAD

**Issue by timsanwald** [CoWolf/CoWolf#29]
- [x] Research: Henshin transformation #30 
- [ ] Research: Ensure #31 
- [ ] Research: Xtext #32 
- [x] Set up Kamai #33 
- [ ] Research: Metamodels and DTMP #34
