### ISSUE TITLE
Performance certification (CTMC)

### ISSUE THREAD

**Issue by timsanwald** [CoWolf/CoWolf#77]
|  |  |
| --- | --- |
| **As an** | End user |
| **I want to** | evaluate the performance model |
| **to** | predict or analyse the performance of my system |

**Subtasks**
- [ ] #154 Create ui to define properties
- [ ] #155 Show results in view
- [ ] #156 Run PRISM performance validation

**Done When:**
- [ ] Transfer the model to the external program model type
- [ ] Provide the properties to calculate the quality
- [ ] Run the external program with the exported model and the properties
- [ ] Nice presentation of the results

**Comment by philippniethammer** [comment]
Assigned: @DavidSteinhart
