### ISSUE TITLE
Restrict Model Semantic

### ISSUE THREAD

**Issue by jonasscheurich** [CoWolf/CoWolf#81]
|  |  |
| --- | --- |
| **As a** | User |
| **I want to** | be sure |
| **to** | have correct models |

**Done when:**
- [x] Research OCL and wiki documentation #84
- [x] OCL in ecore #85
- [x] OCL as Henshin Rules #86
- [x] Run OCL validation automatically #87
- [x] Solution to show warnings in issue-browser (tab) #88
- [x] OCL for DTMC #89
- [x] OCL for Statecharts #90
