### ISSUE TITLE
Graphical editing (DTMC)

### ISSUE THREAD

**Issue by timsanwald** [CoWolf/CoWolf#9]
|  |  |
| --- | --- |
| **As an** | End user |
| **I want to** | edit a dtmc in an graphical editor |
| **to** | see changes immediately |

**Done When:**
- [ ] Show the DTMC model #206
- [ ] Edit the DTMC model (Create and change graphical elements) #207

**Follows:**
- [ ] #21 Create reliability model (DTMC)
