### ISSUE TITLE
Deployment of a P2 update site

### ISSUE THREAD

**Issue by chrisber** [CoWolf/CoWolf#98]
|  |  |
| --- | --- |
| **As a** | User |
| **I want to** | have a p2 update site (p2 repository) |
| **to** | install the CoWolf Software in Eclipse |

**Done when:**
- [ ] Maven verify life-cycle passes #101
- [ ]  P2 repository available on the server #99
- [ ] Workflow for adding plugin dependencies #102

**Comment by philippniethammer** [comment]
Assigned (Sprint 3+4): @chrisber
